### ISSUE TITLE
no marshal_dump is defined for class Mutex

### ISSUE THREAD

**Issue by mjy** [mx3/mx#12] opened 2011-09-22 14:52 UTC
This is perhaps a problem with the named_scopes that uses regexes or some character encoding.  Looking into fixing this now.

**Comment by caryfitzhugh** [comment] 2011-09-26 02:25
I feel like this has come up recently... I'll try git-bisect...

**Comment by caryfitzhugh** [comment] 2011-09-26 02:58
Phooey.. nope.  It's been broke at least since I had started to help.
Can you reproduce it?

**Comment by mjy** [comment] 2011-09-26 03:21
Yes, I can.  It is related to either 1) named scopes, or 2) character
encoding. I tracked down the problem originally by commenting out
various lines in the controllers.

On Sun, Sep 25, 2011 at 10:58 PM, caryfitzhugh
reply@reply.github.com
wrote:

**Comment by mjy** [comment] 2011-10-24 02:19
Are there places other than content/list that throw this error?  Might be able to close it now.

**Comment by caryfitzhugh** [comment] 2012-01-09 02:24
I haven't seen this in a long time -- I'll just close it.

**Closed as completed by caryfitzhugh** 2012-01-09 02:24 UTC
Labels: blocker
